parser: babel-eslint

extends:
  - eslint:recommended
  - standard
  - standard-react

env:
  node: true
  browser: true
  jest: true

rules:
  # stylistic
  array-bracket-spacing: 2
  comma-dangle: [2, always-multiline]
  eol-last: 2
  object-curly-spacing: [2, always]
  quotes: ["error", "single"]
  semi: ["error", "never"]

  # eslint
  no-unused-vars: [2, { argsIgnorePattern: ^_, varsIgnorePattern: ^_ }]

  # react
  react/display-name: 0
  react/sort-prop-types: 2

  indent: ["error", 2]
